ARG BASE_IMAGE=bfd-base-centos7
FROM ${BASE_IMAGE}

RUN yum install -y \
    iproute \
    && yum clean all

# Copy BFD source and tests
COPY files/ /opt/bfd/files/
COPY importconf /opt/bfd/importconf
COPY bfd-watch.init /opt/bfd/bfd-watch.init
COPY bfd-watch.service /opt/bfd/bfd-watch.service
COPY bfd.service /opt/bfd/bfd.service
COPY cron /opt/bfd/cron
COPY cron.daily /opt/bfd/cron.daily
COPY install.sh /opt/bfd/install.sh
COPY uninstall.sh /opt/bfd/uninstall.sh
COPY bfd.1 /opt/bfd/bfd.1
COPY bfd.bash-completion /opt/bfd/bfd.bash-completion
COPY tests/ /opt/tests/

WORKDIR /opt/tests
CMD ["bats", "--formatter", "tap", "/opt/tests/"]
