#!/bin/bash
# installation path
INSTALL_PATH="/usr/local/ald"

# rule files path
RULES_PATH="$INSTALL_PATH/rules"

# track log script path
TLOG_PATH="$INSTALL_PATH/tlog"

ALERT_EMAIL="ryanm@asmallorange.com"
ALERT_SYSLOG="1"

CHECK_ASN="1"
CHECK_ISP="1"
CHECK_COUNTRY="1"

##
#
whois=`which whois`
geoip=`which geoiplookup`
aswserv="v4.whois.cymru.com"
#   whois -h v4.whois.cymru.com $i | grep -vE "\[|AS Name" | awk '{print$1" "$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15}' >> $out.$file

get_authlist() {
        for rule in `ls $RULES_PATH`; do
                LOG=""
                echo "processing auth rule $rule"
        done
}

